##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [84]:
import numpy as np
dizi = np.random.randint(10, size = 10)
print(dizi)
print((dizi.ndim))
print((dizi.size))
print((dizi.dtype))

[5 9 5 3 1 2 8 1 0 8]
1
10
int32


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [108]:
array1= np.array([[1,2,6,7], [4,3,9,5]])
array2= np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
print(array1.ndim, array2.ndim)
print("satır ve sütün sayıları sırayla" ,array1.shape[0],array1.shape[1],array2.shape[1],array2.shape[2])
print(array1.size, array2.size)

2 3
satır ve sütün sayıları sırayla 2 4 2 3
8 12


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [110]:
array1[0,1]

2

In [112]:
array1[0,3]

7

In [130]:
array2[1,1,2]

9

In [162]:
array2[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [187]:
array1[0,1:3]

array([2, 6])

In [191]:
array1[1,1:4]

array([3, 9, 5])

In [195]:
array2[0, 1, :]

array([21,  8, 11])

In [197]:
array2[1, 0, 1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [233]:
a = np.zeros((5,3))
b = np.ones((5,3))
dizi = np.concatenate([a,b])
dizi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])